apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: {{ include "mysql-single.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mysql-single.name" . }}
    helm.sh/chart: {{ include "mysql-single.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.mysql.replicas }}
  secretName: {{ template "mysql-single.fullname" . }}-cluster
  mysqlVersion: {{ .Values.mysql.version | quote }}
  podSpec:
    resources:
{{ toYaml .Values.mysql.resources | indent 8 }}
  volumeSpec:
{{ toYaml .Values.mysql.volumeSpec | indent 4 }}
{{- with fromYaml .Values.mysql.conf }}
  mysqlConf:
{{ toYaml . | indent 4 }}
{{- end }}
