mysql:
  version: "5.7-stretch"
  database: ""
  user: ""
  password: ""
  root_password: ""
  backupSchedule: ""
  backupName: ""
  backupSecretName: ""
  replicas: 3
  conf: ""
  #"thread-cache-size: \"150\"\n"

  allowExternal: true
  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    requests:
      cpu: 200m
      memory: 256Mi
  # Based on PersistentVolumeClaimSpec
  volumeSpec:
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 10Gi

phpmyadmin:
  enabled: true
  existingSecret: ""
  image:
    registry: docker.io
    repository: phpmyadmin/phpmyadmin
    tag: 4.8
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    annotations: {}
     # kubernetes.io/ingress.class: traefik
     # ingress.kubernetes.io/ssl-redirect: "false"
     # traefik.frontend.rule.type: PathPrefix
    hosts:
    - "phpmyadmin.dev.banzaicloud.com"
    # - "domain.com/xyz"
    # - "domain.com"
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local